"""My Migration

Revision ID: d163df8a116c
Revises: 4c966dee7d2b
Create Date: 2025-08-15 22:38:55.766227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd163df8a116c'
down_revision: Union[str, Sequence[str], None] = '4c966dee7d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(), nullable=True),
    sa.Column('E-mail', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_index(op.f('ix_Users_E-mail'), 'Users', ['E-mail'], unique=True)
    op.create_index(op.f('ix_Users_UserID'), 'Users', ['UserID'], unique=False)
    op.create_index(op.f('ix_Users_UserName'), 'Users', ['UserName'], unique=True)
    op.create_table('Notes',
    sa.Column('NoteID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('NoteID')
    )
    op.create_index(op.f('ix_Notes_NoteID'), 'Notes', ['NoteID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Notes_NoteID'), table_name='Notes')
    op.drop_table('Notes')
    op.drop_index(op.f('ix_Users_UserName'), table_name='Users')
    op.drop_index(op.f('ix_Users_UserID'), table_name='Users')
    op.drop_index(op.f('ix_Users_E-mail'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
